[package]
name = "raklib"
version = "0.1.0"
authors = ["green"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[profile.release]
debug = true

[dependencies]